blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path("<int:pk>/", cache_page(200)(BlogDetailView.as_view()), name="blog_detail")
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("message.urls", namespace="message")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.urls import path

from message.apps import MessageConfig
from message.views import (
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    ClientListView,
    ClientDetailView,
    ClientCreateView,
    ClientUpdateView,
    ClientDeleteView,
    MailingListListView,
    MailingListDetailView,
    MailingListCreateView,
    MailingListUpdateView,
    MailingListDeleteView,
    toggle_status,
    AttemptListView,
    HomePageView,
)

app_name = MessageConfig.name

urlpatterns = [
    path("", HomePageView, name="home_page_view"),
    path("messages/", MessageListView.as_view(), name="message_view"),
    path("message/<int:pk>", MessageDetailView.as_view(), name="message_detail"),
    path("message/create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "message/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message/<int:pk>/delete-confirm/",
        MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path("clients/", ClientListView.as_view(), name="client_view"),
    path("clients/<int:pk>", ClientDetailView.as_view(), name="client_detail"),
    path("clients/create/", ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path(
        "clients/<int:pk>/delete-confirm/",
        ClientDeleteView.as_view(),
        name="client_delete",
    ),
    path("mailing-list/", MailingListListView.as_view(), name="mailinglist_view"),
    path(
        "mailing-list/<int:pk>",
        MailingListDetailView.as_view(),
        name="mailinglist_detail",
    ),
    path(
        "mailing-list/create/",
        MailingListCreateView.as_view(),
        name="mailinglist_create",
    ),
    path(
        "mailing-list/<int:pk>/update/",
        MailingListUpdateView.as_view(),
        name="mailinglist_update",
    ),
    path(
        "mailing-list/<int:pk>/delete/",
        MailingListDeleteView.as_view(),
        name="mailinglist_delete",
    ),
    path("mailing-list/<int:pk>/activate/", toggle_status, name="toggle_status"),
    path("mailing-list/<int:pk>/attempt/", AttemptListView, name="attempt_list"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    UserRegisterView,
    email_verification,
    UserDetailView,
    UserUpdateView,
    UserListView,
    toggle_is_active,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("email-confirm/<str:token>", email_verification, name="email_confirm"),
    path("profiles/view", UserListView.as_view(), name="user_view"),
    path("profile/<int:pk>", UserDetailView.as_view(), name="user_detail"),
    path("profile/<int:pk>/update", UserUpdateView.as_view(), name="user_update"),
    path("profile/<int:pk>/confirm-delete", UserUpdateView.as_view(), name="user_delete"),
    path("profile/<int:pk>/activate", toggle_is_active, name="toogle_activate"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    Модель Пользователя
    """

    username = None

    email = models.EmailField(
        unique=True,
        verbose_name="Email",
    )
    avatar = models.ImageField(
        upload_to="users/", verbose_name="Аватар", blank=True, null=True
    )
    token = models.CharField(max_length=50, verbose_name="Токен", blank=True, null=True)
    first_name = models.CharField(
        max_length=50,
        verbose_name="Имя",
        blank=True,
        null=True,
    )
    last_name = models.CharField(
        max_length=50, verbose_name="Фамилия", blank=True, null=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_edit_is_active", "can_edit_is_active"),
        ]
        ordering = ("id",)

    def __srt__(self):
        return self.email

    def delete(self, *args, **kwargs):
        """
        Удаляет изображение аватара при удалении пользователя
        """
        self.avatar.delete()
        super(User, self).delete(*args, **kwargs)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from message.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """
    Форма для регистрации пользователя
    """
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserUpdateForm(StyleFormMixin, ModelForm):
    """
    Форма для редактирования профиля пользователя
    """
    class Meta:
        model = User
        fields = ("avatar", "first_name", "last_name")


class UserModeratorForm(StyleFormMixin, ModelForm):
    """
    Форма для редактирования профиля пользователя в режиме модератора
    """
    class Meta:
        model = User
        fields = ("is_active",)

users/views.py
import secrets

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserUpdateForm, UserModeratorForm
from users.models import User


class UserRegisterView(CreateView):
    """
    Форма создания нового пользователя
    """
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}"
        send_mail(
            "Подтверждение почты",
            f"Перейдите по ссылке для подтверждения почты: {url}",
            EMAIL_HOST_USER,
            [user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    """
    Перевод пользователя в статуc Активный при проходе по ссылке с почты
    """
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class UserDetailView(LoginRequiredMixin, DetailView):
    """
    Вывод информации о пользователе
    """
    model = User


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """
    Вывод списка всех пользователей
    """
    model = User
    permission_required = ("users.view_user",)

    def get_queryset(self):
        """
        Возвращает всех пользователей, кроме суперпользователя
        """
        queryset = super().get_queryset()
        if self.request.user.is_superuser:
            queryset = queryset.exclude(is_superuser=True)
        elif self.request.user.is_staff:
            queryset = queryset.exclude(is_staff=True)
        return queryset


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy("message:message_list")

    def get_success_url(self):
        return reverse("users:user_detail", kwargs={"pk": self.object.pk})

    def get_form_class(self):
        """
        Отображает форму редактирования в зависимости от пользователя
        """
        profile = self.request.user
        if profile.is_superuser or profile == self.object:
            return UserUpdateForm
        if profile.has_perm("users.can_edit_is_active"):
            return UserModeratorForm
        raise PermissionDenied


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Вывод формы удаления пользователя
    """
    model = User
    success_url = reverse_lazy("users:user_view")

    def test_func(self):
        """
        Проверка пользователя на принадлежность к суперпользователю
        """
        return self.request.user.is_superuser


@login_required
@permission_required("users.can_edit_is_active")
def toggle_is_active(request, pk):
    """
    Включает/выключает активность пользователя
    """
    user = get_object_or_404(User, pk=pk)
    if user.is_active:
        user.is_active = False
    elif not user.is_active:
        user.is_active = True
    user.save(update_fields=["is_active"])
    return redirect(reverse("users:user_view"))

users/templates/users/login.html
{% extends 'message/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        Вход
    </h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Войти
                        </button>
                        <a class="btn btn-outline-primary" href="{% url 'message:home_page_view'%}"
                           role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


    {% endblock %}

users/templates/users/register.html
{% extends 'message/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        Регистрация аккаунта
    </h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Зарегистрировать
                        </button>
                        <a class="btn btn-outline-primary" href="{% url 'message:home_page_view'%}"
                           role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


    {% endblock %}

users/templates/users/user_detail.html
{% extends 'message/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Данные профиля</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% if object.avatar %}
                    <img class="card-img-top" src="{{ object.avatar| mymedia }}"
                         style="max-width: 600px; max-height: 400px">
                    {% else %}
                    <img src="/media/dd70ce88-0468-427b-9b4b-e3b4b4ddf6f0.jpeg"
                         style="max-width: 400px; max-height: 190px">
                    {% endif %}
                    <br>
                    <br>
                    <h4>Email:</h4>
                    <p>{{ object.email }}</p>
                    <h4>Имя:</h4>
                    <p>{{ object.first_name }}</p>
                    <h4>Фамилия:</h4>
                    <p> {{ object.last_name }}</p>
                    <a href="{% url 'users:user_update' user.pk %}" type="button"
                       class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>

                </div>
            </div>
        </div>
    </div>


    {% endblock %}

users/templates/users/user_form.html
{% extends 'message/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">
        Изменение данных профиля
    </h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Сохранить
                        </button>
                        <a class="btn btn-outline-primary" href="{% url 'users:user_detail' user.pk %}"
                           role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


    {% endblock %}

users/templates/users/user_list.html
{% extends 'message/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Список пользователей</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="row">
            {% for profile in object_list %}
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-7 d-flex align-items-center justify-content-center">
                                <h4 class="my-0 font-weight-normal">{{ profile.email | truncatechars:60 }}</h4>
                            </div>
                            <div class="col-5">
                                <div class="d-grid gap-2">
                                    {% if profile.is_active %}
                                    <a class="btn btn-lg btn-block btn-outline-danger form-control"
                                       style="float: right;" href="{% url 'users:toogle_activate' profile.pk %}"
                                       role="button">Заблокировать</a>
                                    {% else %}
                                    <a class="btn btn-lg btn-block btn-outline-success form-control"
                                       style="float: right;" href="{% url 'users:toogle_activate' profile.pk %}"
                                       role="button">Разблокировать</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    {% endblock %}