blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path("<int:pk>/", cache_page(200)(BlogDetailView.as_view()), name="blog_detail")
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("message.urls", namespace="message")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.urls import path

from message.apps import MessageConfig
from message.views import (
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageUpdateView,
    MessageDeleteView,
    ClientListView,
    ClientDetailView,
    ClientCreateView,
    ClientUpdateView,
    ClientDeleteView,
    MailingListListView,
    MailingListDetailView,
    MailingListCreateView,
    MailingListUpdateView,
    MailingListDeleteView,
    toggle_status,
    AttemptListView,
    HomePageView,
)

app_name = MessageConfig.name

urlpatterns = [
    path("", HomePageView, name="home_page_view"),
    path("messages/", MessageListView.as_view(), name="message_view"),
    path("message/<int:pk>", MessageDetailView.as_view(), name="message_detail"),
    path("message/create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "message/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message/<int:pk>/delete-confirm/",
        MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path("clients/", ClientListView.as_view(), name="client_view"),
    path("clients/<int:pk>", ClientDetailView.as_view(), name="client_detail"),
    path("clients/create/", ClientCreateView.as_view(), name="client_create"),
    path("clients/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path(
        "clients/<int:pk>/delete-confirm/",
        ClientDeleteView.as_view(),
        name="client_delete",
    ),
    path("mailing-list/", MailingListListView.as_view(), name="mailinglist_view"),
    path(
        "mailing-list/<int:pk>",
        MailingListDetailView.as_view(),
        name="mailinglist_detail",
    ),
    path(
        "mailing-list/create/",
        MailingListCreateView.as_view(),
        name="mailinglist_create",
    ),
    path(
        "mailing-list/<int:pk>/update/",
        MailingListUpdateView.as_view(),
        name="mailinglist_update",
    ),
    path(
        "mailing-list/<int:pk>/delete/",
        MailingListDeleteView.as_view(),
        name="mailinglist_delete",
    ),
    path("mailing-list/<int:pk>/activate/", toggle_status, name="toggle_status"),
    path("mailing-list/<int:pk>/attempt/", AttemptListView, name="attempt_list"),
]

message/forms.py
from datetime import datetime

from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField, TextInput, DateTimeField

from message.models import Message, Client, MailingList


class StyleFormMixin:
    """
    Mixin для стилизации формы.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            elif isinstance(field, DateTimeField):
                field.widget.attrs["class"] = "form-datetime-input"
            else:
                field.widget.attrs["class"] = "form-control"


class MessageForm(StyleFormMixin, ModelForm):
    """
    Форма для создания нового сообщения
    """
    class Meta:
        model = Message
        fields = ("title_letter", "body_letter")
        widgets = {
            "title_letter": TextInput(attrs={"placeholder": "Введите тему сообщения"}),
        }


class ClientForm(StyleFormMixin, ModelForm):
    """
    Форма для создания нового клиента
    """
    class Meta:
        model = Client
        fields = ("name", "email", "comment")
        widgets = {
            "name": TextInput(attrs={"placeholder": "Введите Ф.И.О."}),
            "email": TextInput(attrs={"placeholder": "Введите Email"}),
            "comment": TextInput(attrs={"placeholder": "Введите текст"}),
        }


class MailingListForm(StyleFormMixin, ModelForm):
    """
    Форма для создания и изменения рассылки сообщения
    """
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super(MailingListForm, self).__init__(*args, **kwargs)
        if not user.is_superuser:
            self.fields["message"].queryset = Message.objects.filter(owner=user)
            self.fields["clients"].queryset = Client.objects.filter(owner=user)

    class Meta:
        model = MailingList
        fields = (
            "message",
            "clients",
            "date_and_time_of_sending",
            "periodicity",
        )

    def clean_message(self):
        """
        Проверяет наличие уже имеющейся рассылки с таким сообщением
        """
        new_message = self.cleaned_data["message"]
        if MailingList.objects.filter(message=new_message.pk).exists():
            raise ValidationError("Рассылка с этим сообщением уже имеется")
        return new_message

    def clean_date_and_time_of_sending(self):
        """
        Проверяет, что дата и время рассылки не меньше текущего.
        """
        date_and_time = self.cleaned_data["date_and_time_of_sending"]
        if date_and_time.timestamp() < datetime.now().timestamp():
            raise ValidationError("Выбранная дата и время меньше текущего")
        return date_and_time


class MailingListUpdateForm(StyleFormMixin, ModelForm):
    """
    Форма для изменения рассылки сообщения
    """
    class Meta:
        model = MailingList
        fields = (
            "message",
            "clients",
            "date_and_time_of_sending",
            "periodicity",
        )

    def clean_date_and_time_of_sending(self):
        """
        Проверяет, что дата и время рассылки не меньше текущего.
        """
        date_and_time = self.cleaned_data["date_and_time_of_sending"]
        if date_and_time.timestamp() < datetime.now().timestamp():
            raise ValidationError("Выбранная дата и время меньше текущего")
        return date_and_time


class MailingListModeratorForm(StyleFormMixin, ModelForm):
    """
    Форма для создания рассылки сообщения
    """
    class Meta:
        model = MailingList
        fields = ("status",)

message/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from blog.models import Blog
from message.forms import (
    MessageForm,
    ClientForm,
    MailingListForm,
    MailingListModeratorForm,
    MailingListUpdateForm,
)
from message.models import Message, Client, MailingList
from message.services import (
    get_total_mailings_active_from_cache,
    get_total_items_from_cache,
)


class MessageListView(ListView):
    """
    Контроллер для отображения всех сообщений
    """
    model = Message

    def get_queryset(self):
        """
        Возвращает сообщения текущего пользователя
        """
        if self.request.user.is_superuser:
            return Message.objects.all()
        elif self.request.user.is_authenticated:
            return Message.objects.filter(owner=self.request.user)
        else:
            return Message.objects.none()


class MessageDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """
    Контроллер для отображения конкретного сообщения
    """
    model = Message

    def test_func(self):
        """
        Проверяет, может ли текущий пользователь просматривать сообщение
        """
        message = self.get_object()
        user = self.request.user
        if user.is_superuser or user == message.owner:
            return True


class MessageCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """
    Контроллер для создания нового сообщения
    """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("message:message_view")

    def form_valid(self, form):
        """
        Сохраняет сообщение в БД и привязывает его к текущему пользователю
        """
        message = form.save()
        message.owner = self.request.user
        message.save(update_fields=["owner"])
        return super().form_valid(form)

    def test_func(self):
        """
        Проверяет, может ли текущий пользователь создать сообщение
        """
        user = self.request.user
        if user.is_superuser or user.is_authenticated and not user.is_staff:
            return True


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для редактирования сообщения
    """
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("message:message_view")

    def get_success_url(self):
        return reverse("message:message_detail", kwargs={"pk": self.object.pk})

    def get_form_class(self):
        """
        Отображает форму редактирования в зависимости от текущего пользователя
        """
        user = self.request.user
        if self.object.owner == user or user.is_superuser:
            return MessageForm
        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Контроллер для удаления сообщения
    """
    model = Message
    success_url = reverse_lazy("message:message_view")

    def test_func(self):
        """
        Проверяет, может ли текущий пользователь удалить конкретное сообщение
        """
        message = self.get_object()
        user = self.request.user
        if user.is_superuser or user == message.owner:
            return True


class ClientListView(LoginRequiredMixin, ListView):
    """
    Контроллер для отображения всех клиентов
    """
    model = Client

    def get_queryset(self):
        """
        Возвращает клиентов текущего пользователя
        """
        if self.request.user.is_superuser:
            return Client.objects.all()
        if self.request.user.is_authenticated:
            return Client.objects.filter(owner=self.request.user)
        else:
            return Client.objects.none()


class ClientDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """
    Контроллер для отображения конкретного клиента
    """
    model = Client

    def test_func(self):
        """
        Проверяет, может ли текущий пользователь просматривать конкретного клиента
        """
        client = self.get_object()
        user = self.request.user
        if user.is_superuser or user == client.owner:
            return True


class ClientCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """
    Контроллер для создания нового клиента
    """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("message:client_view")

    def form_valid(self, form):
        """
        Сохраняет клиента в БД и привязывает его к текущему пользователю
        """
        client = form.save()
        client.owner = self.request.user
        client.save(update_fields=["owner"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("message:client_detail", kwargs={"pk": self.object.pk})

    def test_func(self):
        """
        Проверяет, может ли текущий пользователь создавать клиентов
        """
        user = self.request.user
        if user.is_superuser or user.is_authenticated and not user.is_staff:
            return True


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для редактирования клиента
    """
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("message:client_view")

    def get_success_url(self):
        return reverse("message:client_detail", kwargs={"pk": self.object.pk})

    def get_form_class(self):
        """
        Отображает форму редактирования в зависимости от текущего пользователя
        """
        user = self.request.user
        if self.object.owner == user or user.is_superuser:
            return ClientForm
        raise PermissionDenied


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Контроллер для удаления клиента
    """
    model = Client
    success_url = reverse_lazy("message:client_view")

    def test_func(self):
        """
        Проверяет, может ли текущий пользователь удалять конкретного клиента
        """
        client = self.get_object()
        user = self.request.user
        if user.is_superuser or user == client.owner:
            return True


class MailingListListView(LoginRequiredMixin, ListView):
    """
    Контроллер для отображения всех рассылок
    """
    model = MailingList

    def get_queryset(self):
        """
        Возвращает рассылки текущего пользователя
        """
        if self.request.user.is_superuser or self.request.user.is_staff:
            return MailingList.objects.all()
        elif self.request.user.is_authenticated:
            return MailingList.objects.filter(owner=self.request.user)


class MailingListCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """
    Контроллер для создания новой рассылки
    """
    model = MailingList
    form_class = MailingListForm

    def get_form_kwargs(self):
        """
        Добавляет исходные данные формы из GET-параметра
        """
        form_kwargs = super().get_form_kwargs()
        form_kwargs["initial"]["message"] = self.request.GET.get("id")
        form_kwargs["user"] = self.request.user
        return form_kwargs

    def form_valid(self, form):
        """
        Обновляет дату следующей отправки при сохранении изменений
        """
        mailing = form.save()
        mailing.owner = self.request.user
        mailing.next_date = mailing.date_and_time_of_sending
        mailing.save(update_fields=["next_date", "owner"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("message:mailinglist_detail", kwargs={"pk": self.object.pk})

    def test_func(self):
        """
        Проверяет, может ли текущий пользователь создавать рассылки
        """
        user = self.request.user
        if user.is_superuser or user.is_authenticated and not user.is_staff:
            return True


class MailingListDetailView(LoginRequiredMixin, DetailView):
    """
    Контроллер для отображения конкретной рассылки
    """
    model = MailingList

    def get_context_data(self, **kwargs):
        """
        Добавляет список клиентов к контексту
        """
        context_data = super().get_context_data(**kwargs)
        context_data["clients"] = self.object.clients.all()
        return context_data


class MailingListUpdateView(LoginRequiredMixin, UpdateView):
    """
    Контроллер для создания новой рассылки
    """
    model = MailingList
    form_class = MailingListUpdateForm

    def form_valid(self, form):
        """
        Обновляет дату следующей отправки и статус рассылки при сохранении изменений
        """
        mailing = form.save()
        mailing.next_date = mailing.date_and_time_of_sending
        mailing.status = "Запущена"
        mailing.save(update_fields=["next_date", "status"])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("message:mailinglist_detail", kwargs={"pk": self.object.pk})

    def get_form_class(self):
        """
        Отображает форму удаления в зависимости от текущего пользователя
        """
        user = self.request.user
        if self.object.owner == user or user.is_superuser:
            return MailingListUpdateForm
        elif user.has_perm("message.can_edit_status"):
            return MailingListModeratorForm


class MailingListDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Контроллер для удаления рассылки
    """
    model = MailingList
    success_url = reverse_lazy("message:mailinglist_view")

    def test_func(self):
        """
        Проверяет, может ли текущий пользователь удалять конкретную рассылку
        """

message/templates/message/attempt_list.html
{% extends 'message/base.html' %}
{% load my_tags1 %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Отчет по отправке {{ mailing }} </h1>
</div>

<div class="container">
    <div class="row text-center">

        <div class="row">
            <p>
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'message:mailinglist_detail' mailing.pk %} "
                   role="button">Назад</a>
            </p>
        </div>
        {% if not attempts %}
        <div class="col-12">
            <h1 class="text-body-secondary">
                Отчетов пока что нет
            </h1>
        </div>
        {% else %}


        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Последняя попытка отправки</th>
                <th scope="col">Статус попытки</th>
                <th scope="col">Ответ почтового сервера</th>
            </tr>
            </thead>
            <tbody>
            {% for attempt in attempts %}
            <tr>
                <th scope="row">{{ numbers | get_number }}</th>
                <td>{{ attempt.date_time_last_attempt }}</td>
                <td>{{ attempt.status }}</td>
                <td>{{ attempt.mail_server_response }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}


    </div>



{% endblock %}

message/templates/message/client_detail.html
{% extends 'message/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Информация о клиенте</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h4>Ф.И.О.:</h4>
                    <h3> {{ client.name }}</h3>
                    <h4>Email:</h4>
                    <p>{{ client.email }}</p>
                    <h4>Комментарий:</h4>
                    <p>{{ client.comment }}</p>
                    <a class="btn btn-primary" href="{% url 'message:client_update' client.pk %}" role="button">Изменить</a>
                    <a class="btn btn-danger" href="{% url 'message:client_delete' client.pk %}" role="button">Удалить</a>
                    <br>
                    <br>
                    <a class="btn btn-outline-primary" href="{% url 'message:client_view' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>


    {% endblock %}

message/templates/message/client_list.html
{% extends 'message/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Клиенты</h1>
</div>

<div class="container">
    <div class="row text-center">
        <p>
            <a class="btn btn-lg btn-block btn-outline-warning"
               href="{% url 'message:client_create' %}"
               role="button">Добавить клиента</a>
        </p>

        <div class="row">
            {% if not object_list %}
            <div class="col-12">
                <h1 class="text-body-secondary">
                Клиентов пока не добавлены
                </h1>
            </div>
            {% endif %}
            {% for client in object_list %}
            <div class="col-6">
                <div class="card mb-4 box-shadow" style="width: 600px; height: 90px">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-7 d-flex align-items-center justify-content-center">
                                <h4 class="my-0 font-weight-normal">{{ client.name }}</h4>
                            </div>
                            <div class="col-5">
                                    <a class="btn btn-lg btn-block btn-outline-primary form-control"
                                       style="float: right;" href="{% url 'message:client_detail' client.pk %}"
                                       role="button">О клиенте</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>
    {% endblock %}

message/templates/message/mailinglist_detail.html
{% extends 'message/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ mailinglist }}</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h4>Сообщение:</h4>
                    <p>{{ mailinglist.message }}
                    <p>
                    <h4>Адреса рассылок:</h4>
                    <p>
                        {% for client in clients %}
                        {{ client }}
                        <br>
                        {% endfor %}
                    </p>
                    <h4>Периодичность рассылки:</h4>
                    <p>{{ mailinglist.periodicity }}
                    <p>
                    <h4>Статус рассылки:</h4>
                    <p>{{ mailinglist.status }}</p>

                    <h4>Время первой отправки:</h4>
                    <p>{{ mailinglist.date_and_time_of_sending }}</p>

                    {% if mailinglist.status == 'Запущена' %}
                    <a class="btn btn-danger" href="{% url 'message:toggle_status' mailinglist.pk %}"
                       role="button">Завершить</a>
                    {% elif mailinglist.status == 'Создана' and not user.is_staff or user.is_superuser %}
                    <a class="btn btn-success" href="{% url 'message:toggle_status' mailinglist.pk %}"
                       role="button">Запустить</a>
                    {% elif mailinglist.status == 'Завершена' and not user.is_staff or user.is_superuser %}
                    <a class="btn btn-success" href="{% url 'message:mailinglist_update' mailinglist.pk %}"
                       role="button">Запустить заново</a>
                    {% endif %}

                    <a class="btn btn-primary" href="{% url 'message:attempt_list' mailinglist.pk %}" role="button">Отчет
                        по отправке
                    </a>
                    {% if not user.is_staff or user.is_superuser %}
                    <a class="btn btn-danger" href="{% url 'message:mailinglist_delete' mailinglist.pk %}"
                       role="button">Удалить
                        рассылку</a>
                    {% endif %}
                    <br>
                    <br>
                    <a class="btn btn-outline-primary" href="{% url 'message:mailinglist_view' %}"
                       role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>


    {% endblock %}

message/templates/message/mailinglist_list.html
{% extends 'message/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Список рассылок</h1>
</div>

<div class="container">
    <div class="row text-center">
        <p>
            {% if user.is_authenticated and not user.is_staff or user.is_superuser %}
            <a class="btn btn-lg btn-block btn-outline-warning"
               href="{% url 'message:mailinglist_create' %}"
               role="button">Создать рассылку</a>
            {% endif %}
        </p>

        <div class="row">
            {% if not object_list %}
            <div class="col-12">
                <h1 class="text-body-secondary">
                    Рассылки еще не созданы
                </h1>
            </div>
            {% endif %}
            {% for mailinglist in object_list %}
            <div class="col-6">
                <div class="card mb-4 box-shadow" style="width: 600px; height: 140px">
                    <div class="card-body" >
                        <div class="row">
                            <div class="col-7 d-flex align-items-center justify-content-center">
                                <h4 class="my-0 font-weight-normal">

                                    {% if mailinglist.status == 'Завершена' %}
                                    <span class="text-muted">
                                        {{ mailinglist }}
                                        <br>
                                        (Завершена)
                                    </span>
                                    {% else %}
                                    {{ mailinglist }}
                                    {% endif %}
                                </h4>
                            </div>
                            <div class="col-5">
                                <div class="d-grid gap-2">
                                    {% if mailinglist.status == 'Запущена' %}
                                    <a class="btn btn-lg btn-block btn-outline-danger form-control"
                                       style="float: right;" href="{% url 'message:toggle_status' mailinglist.pk %}"
                                       role="button">Завершить</a>
                                    {% elif mailinglist.status == 'Завершена' and not user.is_staff or user.is_superuser %}
                                    <a class="btn btn-lg btn-block btn-outline-success form-control"
                                       style="float: right;"
                                       href="{% url 'message:mailinglist_update' mailinglist.pk %}"
                                       role="button">Запустить заново</a>
                                    {% elif mailinglist.status == 'Создана' and not user.is_staff or user.is_superuser %}
                                    <a class="btn btn-lg btn-block btn-outline-success form-control"
                                       style="float: right;" href="{% url 'message:toggle_status' mailinglist.pk %}"
                                       role="button">Запустить</a>
                                    {% endif %}
                                    <a class="btn btn-lg btn-block btn-outline-primary form-control"
                                       style="float: right;"
                                       href="{% url 'message:mailinglist_detail' mailinglist.pk %}"
                                       role="button">О рассылке</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>
    {% endblock %}

message/templates/message/message_detail.html
{% extends 'message/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Cообщение</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ message.title_letter }}</h2>
                </div>
                <div class="card-body">
                    <p>{{ message.body_letter}}</p>
                    <a class="btn btn-primary" href="{% url 'message:message_update' message.pk %}" role="button">Изменить сообщение</a>
                    <a class="btn btn-danger" href="{% url 'message:message_delete' message.pk %}" role="button">Удалить сообщение</a>
                    <br>
                    <br>
                    <a class="btn btn-outline-primary" href="{% url 'message:message_view' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>


    {% endblock %}

message/templates/message/message_list.html
{% extends 'message/base.html' %}
{% block content %}
{% if user.is_authenticated and not user.is_staff or user.is_superuser %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Cообщения для рассылки</h1>
</div>
{% endif %}

<div class="container">
    <div class="row text-center">
        <p>
            {% if user.is_authenticated and not user.is_staff or user.is_superuser%}
            <a class="btn btn-lg btn-block btn-outline-warning"
               href="{% url 'message:message_create' %}"
               role="button">Новое сообщение</a>
            {% endif %}
        </p>
        <div class="row">
            {% if not object_list and not user.is_staff %}
            <div class="col-12">
                <h1 class="text-body-secondary">
                    Сообщения пока не созданы
                </h1>
            </div>
            {% else %}
            {% for message in object_list %}
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-7 d-flex align-items-center justify-content-center">
                                <h4 class="my-0 font-weight-normal">{{ message.title_letter | truncatechars:60 }}</h4>
                            </div>
                            <div class="col-5">
                                <div class="d-grid gap-2">
                                    <a class="btn btn-lg btn-block btn-outline-success form-control"
                                       style="float: right;" href="{% url 'message:mailinglist_create' %}?id={{ message.id}}"
                                       role="button">Создать рассылку</a>
                                    <a class="btn btn-lg btn-block btn-outline-primary form-control"
                                       style="float: right;" href="{% url 'message:message_detail' message.pk %}"
                                       role="button">О сообщение</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>

    {% endblock %}